DROP TABLE IF EXISTS MACHINE_CONFIG;
CREATE TABLE MACHINE_CONFIG (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  lastaudit DATE NOT NULL,
  PRIMARY KEY (id));
  
DROP TABLE IF EXISTS SOURCE;
DROP TABLE IF EXISTS TARGET;

CREATE TABLE SOURCE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  career VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TARGET (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL
);
 